
package com.mycompany.transformar;

import java.text.DecimalFormat;


public class Conversor extends javax.swing.JFrame {
    
    public static String conclusion = "";
    
    public Conversor() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ElegirMoneda = new javax.swing.JComboBox<>();
        CambiarMoneda = new javax.swing.JButton();
        Salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Monedas");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Elige la moneda a la que deseas convertir");

        ElegirMoneda.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        ElegirMoneda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Soles a Dolares", "Soles a Euro", "Soles a Libras Esterlinas", "Soles a Yen Japonés", "Soles a Won sul-coreano", "Dolares a Soles", "Euro a Soles", "Libras Esterlinas a Soles", "Yen Japonés a Soles", "Won sul-coreano a Soles" }));
        ElegirMoneda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ElegirMonedaMouseClicked(evt);
            }
        });

        CambiarMoneda.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        CambiarMoneda.setText("Ok");
        CambiarMoneda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CambiarMonedaMouseClicked(evt);
            }
        });

        Salir.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Salir.setText("Cancel");
        Salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SalirMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ElegirMoneda, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CambiarMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Salir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(ElegirMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CambiarMoneda)
                    .addComponent(Salir))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CambiarMonedaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CambiarMonedaMouseClicked
        /*- Convertir de la moneda de tu país a Dólar
       - Convertir de la moneda de tu país  a Euros
       - Convertir de la moneda de tu país  a Libras Esterlinas
       - Convertir de la moneda de tu país  a Yen Japonés
       - Convertir de la moneda de tu país  a Won sul-coreano*/
       
        DecimalFormat df = new DecimalFormat("#.00");
       
        String resultado = "", tipo = "";
        String mensaje = "";
        int cambio = ElegirMoneda.getSelectedIndex();
        Cantidad recibe = new Cantidad();
        Double decimal = Double.parseDouble(recibe.cantidad);
        if(cambio == 0){
            resultado = df.format(decimal * 3.74);
            tipo = "Dolares";
        }
        else if(cambio == 1){
            resultado = df.format(decimal * 4.07);
            tipo = "Euros";
        }
        else if(cambio == 2){
            resultado = df.format(decimal * 4.67);
            tipo = "Libras Esterlinas";
        }
        else if(cambio == 3){
            resultado = df.format(decimal * 0.028);
            tipo = "Yen Japonés";
        }
        else if(cambio == 4){
            resultado = df.format(decimal * 0.0028);
            tipo = "Won sul-coreano";
        }
        else if(cambio == 5){
            resultado = df.format(decimal / 3.76);
            tipo = "Soles";
        }
        else if(cambio == 6){
            resultado = df.format(decimal / 4.07);
            tipo = "Soles";
        }
        else if(cambio == 7){
            resultado = df.format(decimal / 4.67);
            tipo = "Soles";
        }
        else if(cambio == 8){
            resultado = df.format(decimal / 0.028);
            tipo = "Soles";
        }
        else if(cambio == 9){
            resultado = df.format(decimal / 0.0028);
            tipo = "Soles";
        }
        
        mensaje = "Tienes $"+resultado+" "+tipo;
        conclusion = mensaje;
        
        Resultado enviar = new Resultado();
        enviar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CambiarMonedaMouseClicked

    private void ElegirMonedaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ElegirMonedaMouseClicked
       
    }//GEN-LAST:event_ElegirMonedaMouseClicked

    private void SalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_SalirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Conversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Conversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Conversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Conversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Conversor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CambiarMoneda;
    private javax.swing.JComboBox<String> ElegirMoneda;
    private javax.swing.JButton Salir;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
